### ISSUE TITLE
关于文章页

### ISSUE THREAD

**Issue by mirosensei** [drrrMikado/drrrMikado.github.io#1]
文章中插入代码过长时会出现页面可以左右移动的现象，其他的问题暂时还没发现OTZ

**Comment by elricli** [comment]
对的。这个是主题Journal的问题。。

**Comment by mirosensei** [comment]
老哥你直接换主题了（滑稽

**Comment by elricli** [comment]
> 老哥你直接换主题了（滑稽

没办法，那个主题代码改不动了，只能给主题提issue，然后先换另外一个了（逃

**Comment by mirosensei** [comment]
我就先 Close 了昂
